### ISSUE TITLE
Features Brainstorm

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/sidewalk-quality-analysis#1]
**Semantic**
- Where did users place labels (per label type) in terms of street location (can use same analysis we used for PS CV paper like % of street segment. Need to discuss this with @tongning and @galenweld to get the code)
   - We may want to distinguish between behavior at an intersection vs. a street
- How often did they go in reverse?
- How much did they check *both* sides of the street?
  - What portion of panorama images user viewed? (e.g., the full 360 degrees?)
- How often did they write in comments?
- What's their average speed (per 100m)?
   - Relatedly, average time per pano
- How often do they place labels? (aka labeling frequency)
- How did they do on the tutorial?
  - Completion time, errors, etc. 
- Did the users click on help?
- How frequently did the user use features like tagging, comments, etc.
- On panos with labels, how long did it take before placing the first label? (i.e., search time)
- Look at distribution of label types vs. best users
- Look at distribution of ratings vs. best users
- How many missions have they already completed

**Low-level events**
- Examine user quality correlated to total mouse movement, keyboard use, mouse clicks, etc.
- Could look at mouse speed/acceleration when placing a label

**Other**
- How often has the user logged in?
- Has the user ever checked their dashboard and if so, how much?
- What is the country of origin (according to reverse ip lookup)?

**Comment by nchowder** [comment]
- How often did the user use the guide images?

**Comment by daotyl000** [comment]
- The average amount of time between clicks

- The average length of comments

- How long to decide that a pano needs no label (for panos without labels)

**Comment by jonfroehlich** [comment]
We should probably split these out now into individual Issues so we can track them. @daotyl000, can you do so?

**Comment by daotyl000** [comment]
For your feature suggestion "Did the users click on help?". How are we able to track this action?

**Comment by jonfroehlich** [comment]
> For your feature suggestion "Did the users click on help?". How are we able to track this action?

@misaugstad are we logging this? If not, we should be. We should be logging every action that the user takes.

> Also for "distribution of ratings vs. best users" does that mean the severity rating of each label?

Yes, my guess is that the distribution of ratings for high-quality PS users will be different from low-quality PS users.

**Comment by misaugstad** [comment]
>@misaugstad are we logging this? If not, we should be. We should be logging every action that the user takes

Yes we are. It is logged in the `webpage_activity` table. The `activity` column should read "Click_module=Help_location=Navbar_route=/audit" if they clicked on "Help" in the navbar on the audit page. Then it would be followed by an entry with the activity = "Visit_Help".

**Comment by jonfroehlich** [comment]
Great!

**Comment by jonfroehlich** [comment]
Cleaner version of this here: https://github.com/ProjectSidewalk/sidewalk-quality-analysis/issues/54
