### ISSUE TITLE
Most of our metrics will have to be normalized...

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/sidewalk-quality-analysis#11]
In thinking through our feature space, most of our metrics will have to be normalized. For example, it's not sufficient to look at the correlation between overall number of keyboard presses or mouse clicks _vs._ accuracy (because users will have completed different numbers of missions, which will inflate numbers). Instead, we need to look some sort of _normalized metric such as the avg. number of keyboard presses (etc.) _per_ something--like per mission, per pano, per 100 meters of auditing distance. We need to decide what this denominator is--and it might be different depending on the feature.

Given this, we may very likely need @misaugstad to run more queries for us in SQL and give us more dumps. For example, right now, we have no way of calculating distance metrics in the log file. If we wanted to enable this in the future, we would need to add in a new logged field on overall distance (_i.e.,_a running tabulating of total meters traveled in our system).

**Comment by jonfroehlich** [comment]
And as I think about this, I think one normalized metric that may work for many situations is 'per pano'... but we should certainly think about this more.

**Comment by daotyl000** [comment]
The normalized metric that we have been using is per pano and per mission. Per pano seems like the best option because if we do per mission or per X meters, not every user might complete each mission or go the whole distance.
