### ISSUE TITLE
Make correlation matrix of input features

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/sidewalk-quality-analysis#16]
See slides 12 and 13 here: https://github.com/jonfroehlich/CSE599Sp2019/blob/master/Lectures/CSE599_L18-FeatureSelectionAndParameterTuning.pdf

Also, Google :)

**Comment by daotyl000** [comment]
From the correlation matrix I have made below, it looks like only a couple of sets of features have a strong correlation with each other. That being Mission completed & panos with over 350 degrees seen (which has a 1 correlation),  Labels confirmed & Tags added, and Mouse clicks with Tags added/Labels confirmed/Mouse movements. Everything else seems to have too weak of a correlation to be significant.

![Screen Shot 2019-08-15 at 9 26 48 AM](https://user-images.githubusercontent.com/28814007/63111424-78fb6980-bf42-11e9-8e52-dd4627e6d7a8.png)
