### ISSUE TITLE
Future SQL Dumps Should Include Header Rows

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/sidewalk-quality-analysis#2]
Future SQL dumps should include a header row... and my Pandas parser is going to expect it...

**Comment by daotyl000** [comment]
Is this an issue that needs to be kept open or can it be closed? It's an ongoing reminder but there isn't an action to go from.

**Comment by misaugstad** [comment]
I just went through all my saved queries and modified the parameters so that they should all include headers by default. I think that should suffice :) Let me know if I send you something in the future without headers and I'll be sure to update that as well.
