### ISSUE TITLE
Meeting Notes 7/9

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/sidewalk-quality-analysis#25]
Meeting notes from 7/9. We should likely tease these apart into separate Issues.

- Look at patterns around 'No Sidewalk' use and whether that's an indicator of quality
- Also, what about correctness of a label in proximity to a 'no sidewalk' label
- Think more about how we may want to label the presence and absence of sidewalks in the future
- Visualize correctness/incorrectness of a label via map-based visualization to explore geographic patterns in correctness (labeling difficulty): https://github.com/ProjectSidewalk/sidewalk-quality-analysis/issues/23
- @nchowder and @daotyl000 work together on setting up full ML pipelines (with SVMs or decision trees) for both inferring labeling correctness and worker quality 
- @nchowder add in new scatter plot with results of radius classifier
- Both @daotyl000 and @daotyl000 need to go through open Issues and make sure they are being addressed
- Have we thought about looking at zone type or population density as a factor in predicting labeling accuracy?

**Comment by jonfroehlich** [comment]
@daotyl000 and @nchowder need to go through this Issue and tease out separate individual Issues that we can track.

**Comment by daotyl000** [comment]
We have gone through and made separate issues addressing all of these bullet points.
