### ISSUE TITLE
Inductively create github 'Labels' for this repo

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/sidewalk-quality-analysis#30]
Look over all Issues in this repo and begin categorizing/tagging them with custom labels (see, for example, the core Sidewalk repo:

![image](https://user-images.githubusercontent.com/1621749/62255471-20f52c80-b3b2-11e9-9286-566e2991647a.png)

**Comment by daotyl000** [comment]
I have labeled every issue before this one and we are continuing to label issues as we make them.
