### ISSUE TITLE
Analyze comments to help determine user quality

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/sidewalk-quality-analysis#37]
Two potential comment related actions we are able to track are number of comments left and the average length of comments. We can use the logged action Contextmenu_textboxChange to determine how many comments were written and in the notes of each action, it records the comment that was left.

**Comment by daotyl000** [comment]
Tracking comments does not appear to be useful for a a couple of reasons:
1. Many users, regardless of accuracy, just don't leave comments at all
2. Out of our sample there is one user in neighborhoods with no sidewalks that wrote long or multiple senteces in the description, way more than other so I'm not sure how much such a big outlier would affect the calculations
3. Of the people who have left comments, they didn't write many

It could be that there isn't enough emphasis on commenting or people might not think its necessary.

![Screen Shot 2019-08-02 at 10 50 02 AM](https://user-images.githubusercontent.com/28814007/62388905-58c7b580-b513-11e9-80ca-026dce1e57f2.png)
![Screen Shot 2019-08-02 at 10 50 07 AM](https://user-images.githubusercontent.com/28814007/62388906-59604c00-b513-11e9-8c9c-6f0aa08a1c2a.png)

**Comment by jonfroehlich** [comment]
Thanks @daotyl000.
