### ISSUE TITLE
Currently no way to associate ml-interactions.csv with ml-users.csv

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/sidewalk-quality-analysis#4]
As far as I can tell, there is currently no way for me to associate the ml-users table with the ml-interactions table. I think each row of the interactions table should include a userid?

Here's the ml-users table:
![image](https://user-images.githubusercontent.com/1621749/59275902-13bd8c00-8c12-11e9-9ee9-b803ef1143ad.png)

and part of the ml-interactions table:
![image](https://user-images.githubusercontent.com/1621749/59275962-394a9580-8c12-11e9-9337-40e45ab41966.png)

**Comment by misaugstad** [comment]
well that is a big oops on my part!

**Comment by jonfroehlich** [comment]
Haha, at least you can tell I’m actually working on this as promised! :-)

**Comment by misaugstad** [comment]
I've sent you a new CSV that includes a user_id field!

**Comment by jonfroehlich** [comment]
Where did you send this to me? I see a Slack message about ml-interactions but not ml-users...

**Comment by misaugstad** [comment]
just to keep track of this on Github: all we needed to do was add user_id column to ml-interactions, no need for a new ml-users file.
