### ISSUE TITLE
Analyze time spent searching  on panos

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/sidewalk-quality-analysis#41]
Does the amount of time a user searches around a pano before their first label has a correlation to their accuracy. This could be determined by the timestamp of when the initial "PanoId_Changed" action and the end point would be the time stamp of the first "ContextMenu_Open" action.

A related topic is how long does that user have to scan around the pano before they determine that the pano doesn't need any label. This could be determined if there are two "PanoId_Changed" actions, using their timestamps for the start and end time

**Comment by jonfroehlich** [comment]
Moved to: https://github.com/ProjectSidewalk/sidewalk-quality-analysis/issues/54
