### ISSUE TITLE
Analyzing User Validation Accuracy

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/sidewalk-quality-analysis#48]
Galen proposed looking into the accuracy of users doing validations by testing for group conciseness on validations. For examples, if there are 3 users who agree with a validation while 1 disagrees, the validation is probably correct. User's validations importance could be scaled differently based off of how much they agree with other user's validations. This would be looked at separately from labeling interaction data and accuracy.

**Comment by jonfroehlich** [comment]
Captured here now: https://github.com/ProjectSidewalk/sidewalk-quality-analysis/issues/54
