### ISSUE TITLE
Analyze Patterns & correctness between No Sidewalk labels & user quality

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/sidewalk-quality-analysis#49]
Does a user's use of the no sidewalk label provide a good indicator for their quality? We have found that users who have to navigate through neighborhoods with poor sidewalk infrastructure perform worse, partially due to being unsure when to label obstructions and surface problems Does the frequency that users place these labels have an effect on their overall quality (frequency in a region w/o sidewalks. How accurate are the other labels around the no sidewalk label? What other patterns can be observed between no sidewalk labels and user quality?

**Comment by jonfroehlich** [comment]
Seems a bit too Seattle centric. Closing for now.
