### ISSUE TITLE
Start San Pedro deployment with only a single neighborhood

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/sidewalk-quality-analysis#58]
![image](https://user-images.githubusercontent.com/1621749/85587272-7d7abf00-b5f6-11ea-86ec-b1e79f7ef416.png)

**Comment by misaugstad** [comment]
hahah wrong repo! just made an issue in the sidewalk repo: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2147
