### ISSUE TITLE
To calculate speed, will need to integrate code from core sidewalk analysis...

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/sidewalk-quality-analysis#9]
In some of our quality inference analyses, we will want to calculate the user's speed (e.g., their average walking speed during a mission). To do this, we will need to calculate distance in meters. For this, I imagine best to use the same calculations that we do in core sidewalk or, at least, in @misaugstad previous analysis code. 

Thoughts @misaugstad?

**Comment by misaugstad** [comment]
so is this something where you want total audited distance as another column in the ml-users file?

**Comment by jonfroehlich** [comment]
Possibly. But I may also need it at a tighter granularity i think... at the very least, at the mission level. 

What other aggregate stats could you offer in the ml-users file?

**Comment by jonfroehlich** [comment]
How about:
- Accuracy per label type
- Num missions completed
- Num labels (and broken down by type)

**Comment by misaugstad** [comment]
>Possibly. But I may also need it at a tighter granularity i think... at the very least, at the mission level.

Okay so I can give you the total audited distance for the user, but I can also add another CSV that has the distance for each mission.

**Comment by jonfroehlich** [comment]
Let's start with the easier one first... no need to create another CSV yet...

**Comment by misaugstad** [comment]
All the stats except for the speed should be super easy. Should be able to do speed as well, it will likely just take a long time to calculate each time.
